### PR TITLE
FIX: Install 'file' package needed by the patch scripts

### PR DESCRIPTION
**Pull request by ironsteel**

### CODE REVIEW

**Comment by zberkes** [comment]
Which application is missing this?

**Comment by ironsteel** [comment]
The checkArch() function in the patches/upgrade-libstdc++ script uses the file command. I've used the your docker image from docker hub and it didn't have installed the file command.

**Comment by zberkes** [comment]
Okay. Sounds strange, I will check it when I will be at home.

**Comment by zberkes** [comment]
I used a version on my computer which contained GCC and therefore file package was installed as its dependency.
I've created a full rebuild of Docker image and uploaded it.
Please note that Docker Hub may need some time to refresh the status.
Please, let me know if it still doesn't work!

**Comment by ironsteel** [comment]
Ok :+1:

**Pull request closed without merging**
